<?php
session_start();

$config = [
    'client_id' => 'MIK9ADXK8L-100',
    'secret_key' => 'W6K799QS6I',
    'redirect_uri' => 'https://9000-firebase-stock-1771082063097.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/fyers_callback',
    'api_base_uri' => 'https://api-t1.fyers.in/api/v3/',
    'stocks_to_track' => [
        // Nifty 50
        "NSE:ADANIENT-EQ", "NSE:ADANIPORTS-EQ", "NSE:APOLLOHOSP-EQ", "NSE:ASIANPAINT-EQ",
        "NSE:AXISBANK-EQ", "NSE:BAJAJ-AUTO-EQ", "NSE:BAJFINANCE-EQ", "NSE:BAJAJFINSV-EQ",
        "NSE:BPCL-EQ", "NSE:BHARTIARTL-EQ", "NSE:BRITANNIA-EQ", "NSE:CIPLA-EQ",
        "NSE:COALINDIA-EQ", "NSE:DIVISLAB-EQ", "NSE:DRREDDY-EQ", "NSE:EICHERMOT-EQ",
        "NSE:GRASIM-EQ", "NSE:HCLTECH-EQ", "NSE:HDFCBANK-EQ", "NSE:HDFCLIFE-EQ",
        "NSE:HEROMOTOCO-EQ", "NSE:HINDALCO-EQ", "NSE:HINDUNILVR-EQ", "NSE:ICICIBANK-EQ",
        "NSE:ITC-EQ", "NSE:INDUSINDBK-EQ", "NSE:INFY-EQ", "NSE:JSWSTEEL-EQ",
        "NSE:KOTAKBANK-EQ", "NSE:LTIM-EQ", "NSE:LT-EQ", "NSE:M&M-EQ", "NSE:MARUTI-EQ",
        "NSE:NTPC-EQ", "NSE:NESTLEIND-EQ", "NSE:ONGC-EQ", "NSE:POWERGRID-EQ",
        "NSE:RELIANCE-EQ", "NSE:SBILIFE-EQ", "NSE:SBIN-EQ", "NSE:SUNPHARMA-EQ",
        "NSE:TATAMOTORS-EQ", "NSE:TCS-EQ", "NSE:TATASTEEL-EQ", "NSE:TATACONSUM-EQ",
        "NSE:TECHM-EQ", "NSE:TITAN-EQ", "NSE:UPL-EQ", "NSE:ULTRACEMCO-EQ", "NSE:WIPRO-EQ",
        // Nifty Next 50
        "NSE:AMBUJACEM-EQ", "NSE:ACC-EQ", "NSE:BANKBARODA-EQ", "NSE:BERGEPAINT-EQ", "NSE:COLPAL-EQ",
        "NSE:DABUR-EQ", "NSE:DMART-EQ", "NSE:DLF-EQ", "NSE:GAIL-EQ", "NSE:GODREJCP-EQ",
        "NSE:HAVELLS-EQ", "NSE:HDFCAMC-EQ", "NSE:ICICIGI-EQ", "NSE:ICICIPRULI-EQ", "NSE:IOC-EQ",
        "NSE:INDIGO-EQ", "NSE:JINDALSTEL-EQ", "NSE:LICI-EQ", "NSE:MARICO-EQ", "NSE:MUTHOOTFIN-EQ",
        "NSE:NAUKRI-EQ", "NSE:PIDILITIND-EQ", "NSE:PGHH-EQ", "NSE:PNB-EQ", "NSE:SAIL-EQ",
        "NSE:SBICARD-EQ", "NSE:SHREECEM-EQ", "NSE:SIEMENS-EQ", "NSE:SRF-EQ", "NSE:SAMVARDHANA-EQ",
        "NSE:TATAPOWER-EQ", "NSE:TRENT-EQ", "NSE:TVSMOTOR-EQ", "NSE:UNIONBANK-EQ", "NSE:VEDL-EQ",
        "NSE:VARUNBEV-EQ", "NSE:YESBANK-EQ", "NSE:ZEEL-EQ", "NSE:ZOMATO-EQ", "NSE:BOSCHLTD-EQ",
        "NSE:CHOLAFIN-EQ", "NSE:HAL-EQ", "NSE:HINDZINC-EQ", "NSE:ADANIGREEN-EQ", "NSE:ADANIENSOL-EQ",
        "NSE:TATACOMM-EQ", "NSE:ABB-EQ"
    ]
];

return $config;